[2021-12-31 02:29:23 +0300] [227697] [INFO] Starting gunicorn 20.1.0
[2021-12-31 02:29:23 +0300] [227697] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (227697)
[2021-12-31 02:29:23 +0300] [227697] [INFO] Using worker: sync
[2021-12-31 02:29:23 +0300] [227734] [INFO] Booting worker with pid: 227734
[2021-12-31 02:29:23 +0300] [227734] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:23 +0300] [227734] [INFO] Worker exiting (pid: 227734)
[2021-12-31 02:29:24 +0300] [227736] [INFO] Booting worker with pid: 227736
[2021-12-31 02:29:24 +0300] [227736] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:24 +0300] [227736] [INFO] Worker exiting (pid: 227736)
[2021-12-31 02:29:24 +0300] [227737] [INFO] Booting worker with pid: 227737
[2021-12-31 02:29:24 +0300] [227737] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:24 +0300] [227737] [INFO] Worker exiting (pid: 227737)
[2021-12-31 02:29:24 +0300] [227697] [WARNING] Worker with pid 227736 was terminated due to signal 15
[2021-12-31 02:29:24 +0300] [227697] [WARNING] Worker with pid 227737 was terminated due to signal 15
[2021-12-31 02:29:24 +0300] [227697] [INFO] Shutting down: Master
[2021-12-31 02:29:24 +0300] [227697] [INFO] Reason: Worker failed to boot.
[2021-12-31 02:29:25 +0300] [227756] [INFO] Starting gunicorn 20.1.0
[2021-12-31 02:29:25 +0300] [227756] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (227756)
[2021-12-31 02:29:25 +0300] [227756] [INFO] Using worker: sync
[2021-12-31 02:29:25 +0300] [227757] [INFO] Booting worker with pid: 227757
[2021-12-31 02:29:25 +0300] [227758] [INFO] Booting worker with pid: 227758
[2021-12-31 02:29:25 +0300] [227759] [INFO] Booting worker with pid: 227759
[2021-12-31 02:29:25 +0300] [227757] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:25 +0300] [227757] [INFO] Worker exiting (pid: 227757)
[2021-12-31 02:29:25 +0300] [227758] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:25 +0300] [227758] [INFO] Worker exiting (pid: 227758)
[2021-12-31 02:29:25 +0300] [227759] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:25 +0300] [227759] [INFO] Worker exiting (pid: 227759)
[2021-12-31 02:29:25 +0300] [227756] [WARNING] Worker with pid 227759 was terminated due to signal 15
[2021-12-31 02:29:25 +0300] [227756] [WARNING] Worker with pid 227758 was terminated due to signal 15
[2021-12-31 02:29:25 +0300] [227756] [INFO] Shutting down: Master
[2021-12-31 02:29:25 +0300] [227756] [INFO] Reason: Worker failed to boot.
[2021-12-31 02:29:25 +0300] [227760] [INFO] Starting gunicorn 20.1.0
[2021-12-31 02:29:25 +0300] [227760] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (227760)
[2021-12-31 02:29:25 +0300] [227760] [INFO] Using worker: sync
[2021-12-31 02:29:25 +0300] [227761] [INFO] Booting worker with pid: 227761
[2021-12-31 02:29:25 +0300] [227761] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:25 +0300] [227761] [INFO] Worker exiting (pid: 227761)
[2021-12-31 02:29:25 +0300] [227762] [INFO] Booting worker with pid: 227762
[2021-12-31 02:29:25 +0300] [227763] [INFO] Booting worker with pid: 227763
[2021-12-31 02:29:25 +0300] [227762] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:26 +0300] [227762] [INFO] Worker exiting (pid: 227762)
[2021-12-31 02:29:26 +0300] [227763] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:26 +0300] [227763] [INFO] Worker exiting (pid: 227763)
[2021-12-31 02:29:26 +0300] [227766] [INFO] Starting gunicorn 20.1.0
[2021-12-31 02:29:26 +0300] [227766] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (227766)
[2021-12-31 02:29:26 +0300] [227766] [INFO] Using worker: sync
[2021-12-31 02:29:26 +0300] [227768] [INFO] Booting worker with pid: 227768
[2021-12-31 02:29:26 +0300] [227768] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:26 +0300] [227768] [INFO] Worker exiting (pid: 227768)
[2021-12-31 02:29:26 +0300] [227766] [INFO] Shutting down: Master
[2021-12-31 02:29:26 +0300] [227766] [INFO] Reason: Worker failed to boot.
[2021-12-31 02:29:27 +0300] [227769] [INFO] Starting gunicorn 20.1.0
[2021-12-31 02:29:27 +0300] [227769] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (227769)
[2021-12-31 02:29:27 +0300] [227769] [INFO] Using worker: sync
[2021-12-31 02:29:27 +0300] [227770] [INFO] Booting worker with pid: 227770
[2021-12-31 02:29:27 +0300] [227770] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:27 +0300] [227770] [INFO] Worker exiting (pid: 227770)
[2021-12-31 02:29:27 +0300] [227771] [INFO] Booting worker with pid: 227771
[2021-12-31 02:29:27 +0300] [227771] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:27 +0300] [227771] [INFO] Worker exiting (pid: 227771)
[2021-12-31 02:29:27 +0300] [227769] [WARNING] Worker with pid 227771 was terminated due to signal 15
[2021-12-31 02:29:27 +0300] [227769] [INFO] Shutting down: Master
[2021-12-31 02:29:27 +0300] [227769] [INFO] Reason: Worker failed to boot.
[2021-12-31 02:29:28 +0300] [227772] [INFO] Starting gunicorn 20.1.0
[2021-12-31 02:29:28 +0300] [227772] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (227772)
[2021-12-31 02:29:28 +0300] [227772] [INFO] Using worker: sync
[2021-12-31 02:29:28 +0300] [227773] [INFO] Booting worker with pid: 227773
[2021-12-31 02:29:28 +0300] [227774] [INFO] Booting worker with pid: 227774
[2021-12-31 02:29:28 +0300] [227773] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:28 +0300] [227773] [INFO] Worker exiting (pid: 227773)
[2021-12-31 02:29:28 +0300] [227774] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:28 +0300] [227774] [INFO] Worker exiting (pid: 227774)
[2021-12-31 02:29:28 +0300] [227775] [INFO] Booting worker with pid: 227775
[2021-12-31 02:29:28 +0300] [227772] [WARNING] Worker with pid 227774 was terminated due to signal 15
[2021-12-31 02:29:28 +0300] [227775] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/www/timetracker-deploy/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-12-31 02:29:28 +0300] [227775] [INFO] Worker exiting (pid: 227775)
[2021-12-31 03:33:52 +0300] [234657] [INFO] Starting gunicorn 20.1.0
[2021-12-31 03:33:52 +0300] [234657] [INFO] Listening at: unix:/home/www/timetracker-deploy/gunicorn/gunicorn.sock (234657)
[2021-12-31 03:33:52 +0300] [234657] [INFO] Using worker: sync
[2021-12-31 03:33:52 +0300] [234691] [INFO] Booting worker with pid: 234691
[2021-12-31 03:33:52 +0300] [234692] [INFO] Booting worker with pid: 234692
[2021-12-31 03:33:53 +0300] [234693] [INFO] Booting worker with pid: 234693
